# Generated by Django 2.1.5 on 2019-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190113_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Викладач')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
