# Generated by Django 2.1.5 on 2019-01-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_profile_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='access',
            new_name='access_profile',
        ),
    ]
