# Generated by Django 2.1.5 on 2019-01-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20190113_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
